---
- name: Mailcatcher role
  block:

    - name: Requirements present
      apt:
        pkg:
          - ruby-dev
          - libsqlite3-dev
        state: present

    - name: Check the latest version of Mailcatcher
      uri:
        url: https://github.com/sj26/mailcatcher/releases/latest
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: mailcatcher_headers

    - name: Debug Mailcatcher URI
      debug:
        msg:
          - "Location: {{ mailcatcher_headers.location }}"
          - "Path: {{ mailcatcher_headers.location | urlsplit('path') }}"
          - "Version: {{ mailcatcher_headers.location | urlsplit('path') | basename }}"
          - "Version number: {{ mailcatcher_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"
        verbosity: 2

    - name: Set a variable for the latest version available
      set_fact:
        mailcatcher_latest: "{{ mailcatcher_headers.location | urlsplit('path') | basename | regex_replace('^v') }}"

    - name: Check if Mailcatcher is installed
      command: which mailcatcher
      check_mode: false
      changed_when: false
      register: mailcatcher_which
      failed_when: mailcatcher_which.rc is not regex('^0|1')

    - name: Check Mailcatcher version when installed
      block:

        - name: Check installed Mailcatcher version
          command: mailcatcher --version
          check_mode: false
          changed_when: false
          register: mailcatcher_version_check

        - name: Set a variable for the installed version of Mailcatcher
          set_fact:
            mailcatcher_installed: "{{ mailcatcher_version_check.stdout | replace('mailcatcher ', '') | trim }}"

        - name: Set a fact if a newer version is available
          set_fact:
            mailcatcher_upgrade: true
          when: mailcatcher_installed is version(mailcatcher_version, '<')

      when: mailcatcher_which.rc == 0

    - name: Install Mailcatcher
      gem:
        name: mailcatcher
        version: "{{ mailcatcher_latest }}"
        state: present
        user_install: false
      when:
        - mailcatcher_latest is defined
        - ( mailcatcher_which.rc == 1 ) or ( mailcatcher_upgrade is defined and mailcatcher_upgrade )
      notify: Restart mailcatcher

    - name: Systemd service file in place
      template:
        src: mailcatcher.service.j2
        dest: /etc/systemd/system/mailcatcher.service
        mode: 0644
      notify: Restart mailcatcher

    - name: Mailcatcher service enabled
      systemd:
        name: mailcatcher
        enabled: true
      notify: Restart mailcatcher

  tags:
    - mailcatcher
...
