---
- name: Mailcatcher
  block:

    - name: Mailcatcher present
      ansible.builtin.include_tasks: install.yml
      when: mailcatcher

    - name: Mailcatcher absent
      ansible.builtin.include_tasks: remove.yml
      when: not mailcatcher

  tags:
    - mailcatcher
...
