---
- name: Restart Mailcatcher
  block:

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
      listen: Reload systemd

    - name: Stop Mailcatcher
      ansible.builtin.systemd:
        name: mailcatcher
        state: stopped
      listen: Restart mailcatcher

    - name: Start Mailcatcher
      ansible.builtin.systemd:
        name: mailcatcher
        state: started
      listen: Restart mailcatcher

  tags:
    - mailcatcher
...
