---
- name: Restart Mailcatcher
  block:

    - name: Stop Mailcatcher
      systemd:
        name: mailcatcher
        state: stopped
      listen: Restart mailcatcher

    - name: Start Mailcatcher
      systemd:
        name: mailcatcher
        state: started
        daemon_reload: true
      listen: Restart mailcatcher

  tags:
    - mailcatcher
...
